name: Tuya Dashboard
version: "1.0.0"
slug: tuya-dashboard
description: Inspect and control your Tuya smart devices from Home Assistant
url: https://github.com/GMetaxakis/tuya-dashboard
arch:
  - amd64
  - aarch64
  - armv7
startup: application
boot: auto
ingress: true
ingress_port: 3000
panel_icon: mdi:devices
panel_title: Tuya Dashboard
ports:
  3000/tcp: null
ports_description:
  3000/tcp: Web interface
map:
  - config:rw
options: {}
schema: {}
